title: deep trader
description: experience is in debt, and learning is assets.
show_downloads: true
google_analytics:
# theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
