name: cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 0
        env:
          GITHUB_TOKEN: ${{ github.token }}