# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the main branch
  repository_dispatch:
    types: test
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-if-trading-day:
    runs-on: ubuntu-latest
    outputs:
      flag: ${{steps.check.outputs.flag}}

    steps:
    - name: Check
      id: check
      run: |
        if curl -s 'http://qt.gtimg.cn/?q=marketStat' | iconv -f gbk -t utf-8 | grep -q 'SH_close_已收盘'; then
          echo "::set-output name=flag::true"
        else
          echo "::set-output name=flag::false"
        fi

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: check-if-trading-day
    # Steps represent a sequence of tasks that will be executed as part of the job
    if: ${{ needs.check-if-trading-day.outputs.falg == 'true' }}
    steps:

    - name: Step 1
      run: |
        echo 'step 1'

    - name: Step 2
      run: |
        echo 'step 2'