# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the main branch
  repository_dispatch:
    types: test
  workflow_dispatch:


env:
  CHECK_TRADING_DAY: ! ${{github.event.client_payload.no_check_trading_day}}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if-trading-day:
    runs-on: ubuntu-latest
    outputs:
      flag: 555

    steps:
    - name: Check
      id: check
      if: false
      run: |
        if curl -s 'http://qt.gtimg.cn/?q=marketStat' | iconv -f gbk -t utf-8 | grep -q 'SH_close_已收盘'; then
          echo "::set-output name=flag::true"
        else
          echo "::set-output name=flag::false"
        fi

  # This workflow contains a single job called "build"
  trade:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    needs: if-trading-day
    steps:

    - name: Step 1
      run: |
        echo 'step 1'
        echo ${{env.CHECK_TRADING_DAY}}
        # exit 1

    - name: Step 2
      run: |
        echo 'step 2'